name: 4. Build Loop
run-name: Build Loop
on:
  workflow_dispatch:
  
  ## Remove the "#" sign from the beginning of the line below to get automated builds on push (code changes in your repository)
  #push:

  ## Remove the "#" sign from the beginning of the two lines below to get automated builds every two months
  #schedule:
    #- cron: '0 17 1 */2 *' # Runs at 17:00 UTC on the 1st in Jan, Mar, May, Jul, Sep and Nov.

jobs:
  secrets:
    uses: ./.github/workflows/validate_secrets.yml
    secrets: inherit
    
  build:
    needs: secrets
    runs-on: macos-12
    steps:
      # Uncomment to manually select latest Xcode if needed
      - name: Select Latest Xcode
        run: "sudo xcode-select --switch /Applications/Xcode_14.1.app/Contents/Developer"

      # Checks-out the repo
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Customize Loop: Download and apply patches
      - name: Customize Loop
        run: | 

          # The lines below add the customizations listed using the CustomizationSelect script
          # The "\" is a continuation character 
          #   the line following a "\" cannot be blank - that causes the Action to never complete
          /bin/bash -c "$(curl -fsSL \
          https://raw.githubusercontent.com/loopandlearn/lnl-scripts/main/CustomizationSelect.sh)" \
          omnipod_cage \
          dexcom_sage \
          dexcom_upload_readings \
          future_carbs_4h \
          low_carb_limit \
          no_auth \
          override_sens \
          limit_loop_cycle_time \
          2002 \
          algorithm_experiments

          # the final customization listed above CANNOT have a continuation character "\"
          # more customizations can be pasted after this line
          
          # For each patch, edit comment line (keep the #) then update curl (and remove the #)
          
          # Submodule Loop patches:
          # Loop: Filename: Localizable.strings Main.strings
          curl https://github.com/unpeng/Loop/commit/d575d456dc33539eb14841dd213ec471ece5a8dc.patch | git apply -v --directory=Loop
          
          # Submodule LoopKit patches:
          # LoopKit: Filename: LoopKitUI/Resources/zh-Hans.lproj/Localizable.strings
          #                    LoopKitUI/Resources/zh-Hans.lproj/InsulinKit.strings
          #                    LoopKit/Resources/zh-Hans.lproj/Localizable.strings
          curl https://github.com/unpeng/LoopKit/commit/c5978cb1a5739d473cfa2827239db338bb148c7c.patch | git apply -v --directory=LoopKit

          # Submodule LoopSupport patches:
          # LoopSupport: Filename: LoopSupportKitUI/zh-Hans.lproj/Localizable.strings
          curl https://github.com/unpeng/LoopSupport/commit/99f09fac3a69fb48a06f0435e1bfcdd0c16ea391.patch | git apply -v --directory=LoopSupport

          # Submodule NightscoutService patches:
          # NightscoutService: Filename: NightscoutServiceKitUI/zh-Hans.lproj/Localizable.strings
          curl https://github.com/unpeng/NightscoutService/commit/b694359795d43ebee97be06358d441b316da82b1.patch | git apply -v --directory=NightscoutService

          # Submodule OmniBLE patches:
          # OmniBLE: Filename: OmniBLE/zh-Hans.lproj/Localizable.strings
          curl https://github.com/unpeng/OmniBLE/commit/63f0ca7cc7c0f73943a86a7861767d30dbc1668b.patch | git apply -v --directory=OmniBLE

          # Submodule OmniKit patches:
          # OmniKit: Filename: OmniKit/Resources/zh-Hans.lproj/Localizable.strings
          #                    OmniKitUI/Resources/zh-Hans.lproj/Localizable.strings
          curl https://github.com/unpeng/OmniKit/commit/e06f47d636b92891d523823d610246ca1e89a09b.patch | git apply -v --directory=OmniKit

          # Submodule rileylink_ios patches:
          # rileylink_ios: Filename: RileyLinkKitUI/zh-Hans.lproj/Localizable.strings
          curl https://github.com/unpeng/rileylink_ios/commit/b5d891e67334d9cf44ce771eec715bb73f71b3f9.patch | git apply -v --directory=rileylink_ios

          # Submodule LoopOnboarding patches:
          # LoopOnboarding: LoopOnboardingKitUI/zh-Hans.lproj/Localizable.strings
          curl https://github.com/unpeng/LoopOnboarding/commit/f58560da05186d24de931ab95f31d9700cc0e7d8.patch | git apply -v --directory=LoopOnboarding

          # Submodule NightscoutService patches:
          # NightscoutService: NightscoutServiceKit/NightscoutService.swift
          curl https://github.com/unpeng/NightscoutService/commit/c11b97a964ce09597c030d779a6fa71dfebec0b6.patch | git apply -v --directory=NightscoutService
          # NightscoutService: NightscoutServiceKit/Extensions/StoredDosingDecision.swift
          curl https://github.com/unpeng/NightscoutService/commit/25130f0eb5aec30777e27d38fdd2fb380f9e91af.patch | git apply -v --directory=NightscoutService

          # Submodule LoopKit patches:
          # LoopKit: Filename: LoopKit/Service/Remote/Actions/Action.swift
          curl https://github.com/unpeng/LoopKit/commit/35cadfb37039d29ba8337ecb81096a620d7f57dc.patch | git apply -v --directory=LoopKit
          # LoopKit: Filename: LoopKit/Service/Remote/Actions/AutomaticDosingStrategyAction.swift
          curl https://github.com/unpeng/LoopKit/commit/ba043ae44721a796983c2b10792b960d8eda982a.patch | git apply -v --directory=LoopKit
          # LoopKit: Filename: LoopKit/DosingDecisionStore.swift
          curl https://github.com/unpeng/LoopKit/commit/59d3fba85ae929ef14f2133b8b243ae6c89f9001.patch | git apply -v --directory=LoopKit
          
          # Submodule Loop patches:
          # Loop: Filename: Loop/Models/Remote/AutomaticDosingStrategyAction.swift
          curl https://github.com/unpeng/Loop/commit/c07221b54325e50eabf3bfbeebe250181e7c5292.patch | git apply -v --directory=Loop
          # Loop: Filename: Loop/Models/RemoteCommand.swift
          curl https://github.com/unpeng/Loop/commit/bacf08cd7a2c38c9cdd11217bdd93b43185ce51a.patch | git apply -v --directory=Loop
          # Loop: Filename: Loop/Managers/DeviceDataManager.swift
          curl https://github.com/unpeng/Loop/commit/444113d49bafba90884495bad71afb08cb2d0b63.patch | git apply -v --directory=Loop          
          # Loop: Filename: Loop/Managers/RemoteDataServicesManager.swift
          curl https://github.com/unpeng/Loop/commit/5c2f1ae3b24f4d9ffa6713799f3e3de7c795b97c.patch | git apply -v --directory=Loop

          # Submodule NightscoutService patches:
          # NightscoutService: NightscoutService.xcodeproj/project.pbxproj
          curl https://github.com/unpeng/NightscoutService/commit/0ee27bff1d4b26ab118a238d79d09bce74a6238c.patch | git apply -v --directory=NightscoutService
          
          # Submodule NightscoutAPIClient patches:
          # NightscoutAPIClient: NightscoutAPIClient.xcodeproj/project.pbxproj
          curl https://github.com/unpeng/NightscoutAPIClient/commit/643746c8ec72ae58f3c6441330ec96d54ceab560.patch | git apply -v --directory=NightscoutAPIClient          

      # Patch Fastlane Match to not print tables
      - name: Patch Match Tables
        run: find /usr/local/lib/ruby/gems -name table_printer.rb | xargs sed -i "" "/puts(Terminal::Table.new(params))/d"
      
      # Build signed Loop IPA file
      - name: Fastlane Build & Archive
        run: fastlane build_loop
        env:
          TEAMID: ${{ secrets.TEAMID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      
      # Upload to TestFlight
      - name: Fastlane upload to TestFlight
        run: fastlane release
        env:
          TEAMID: ${{ secrets.TEAMID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      # Upload IPA and Symbols
      - name: Upload IPA and Symbol artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            artifacts
            buildlog
